version: '2'
services:
  app:
    image: petclinic
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql
    volumes: 
    - /home/workshop/docker/database_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=petclinic 
      - MYSQL_USER=petclinic 
      - MYSQL_PASSWORD=petclinic

